//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhuyvetterBeton.Beton
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soorten_Hulpstof
    {
        public int ID { get; set; }
        public string Naam { get; set; }
    }
}
