//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhuyvetterBeton.Beton.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\jan\\Desktop\\DB\\DB_ST" +
            "RAATNAMEN.mdf;Integrated Security=True")]
        public string Dhuyvetter_StraatNamenConnectie {
            get {
                return ((string)(this["Dhuyvetter_StraatNamenConnectie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.10.22,1434\\SQLEXPRESS;Initial Catalog=Dhuyvetbestelling;User " +
            "ID=sa;Password=nYHZgDE5hG3rttU3;")]
        public string Dhuyvetter_BestellingConnectie {
            get {
                return ((string)(this["Dhuyvetter_BestellingConnectie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHUAPP02\\SQLEXPRESS;Initial Catalog=DhuyvetLevering;User ID=sa;Passwo" +
            "rd=nYHZgDE5hG3rttU3;")]
        public string Dhuyvetter_LeveringConnectie {
            get {
                return ((string)(this["Dhuyvetter_LeveringConnectie"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHUAPP02\\SQLEXPRESS;Initial Catalog=Dhuyvetbestellling;User ID=sa;Pas" +
            "sword=nYHZgDE5hG3rttU3")]
        public string DhuyvetBestelllingConnectionString {
            get {
                return ((string)(this["DhuyvetBestelllingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHUAPP02\\SQLEXPRESS;Initial Catalog=DhuyvetLevering;User ID=sa;Passwo" +
            "rd=nYHZgDE5hG3rttU3")]
        public string DhuyvetLeveringConnectionString {
            get {
                return ((string)(this["DhuyvetLeveringConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DHUAPP02\\SQLEXPRESS;Initial Catalog=Dhuyvetbestelling;User ID=sa;Pass" +
            "word=nYHZgDE5hG3rttU3")]
        public string DhuyvetbestellingConnectionStringtest {
            get {
                return ((string)(this["DhuyvetbestellingConnectionStringtest"]));
            }
        }
    }
}
